-- Migrations 050–059, in order.
-- Generated by scripts/bundle-migrations.mjs. Safe to run more than once.

-- ============================================================
-- 050_requests_lifecycle.sql
-- ============================================================

-- "Ask for it" had no life after publication: no status, no way to close or
-- delete an ask, and the budget, intent and radius the renter picked were
-- glued into the description text, so nothing could search or sort by them.
--
-- Adds the lifecycle columns, promotes the buried fields, and gives asks a
-- real expiry (the detail screen already claimed they expire).

alter table public.requests
  add column if not exists status text not null default 'open',
  add column if not exists fulfilled_at timestamptz,
  add column if not exists fulfilled_listing_id uuid,
  add column if not exists intent text,
  add column if not exists budget_cents integer,
  add column if not exists radius_miles integer,
  add column if not exists expires_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'requests_status_check'
  ) then
    alter table public.requests
      add constraint requests_status_check
      check (status in ('open', 'fulfilled', 'cancelled'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'requests_intent_check'
  ) then
    alter table public.requests
      add constraint requests_intent_check
      check (intent is null or intent in ('rent', 'buy', 'either'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'requests_budget_check'
  ) then
    alter table public.requests
      add constraint requests_budget_check
      check (budget_cents is null or (budget_cents >= 0 and budget_cents <= 100000000));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'requests_radius_check'
  ) then
    alter table public.requests
      add constraint requests_radius_check
      check (radius_miles is null or (radius_miles > 0 and radius_miles <= 500));
  end if;
end $$;

create index if not exists requests_status_idx on public.requests (status);
create index if not exists requests_expires_at_idx on public.requests (expires_at);

-- Asks that predate this migration run out 30 days after they were posted,
-- same as new ones.
update public.requests
set expires_at = created_at + interval '30 days'
where expires_at is null;

-- A fresh ask is always open and always expires; the client does not get to
-- publish one that outlives the neighborhood's interest in it.
create or replace function public.requests_guard_insert()
returns trigger
language plpgsql
as $$
begin
  new.status := 'open';
  new.fulfilled_at := null;
  new.fulfilled_listing_id := null;
  new.updated_at := now();

  if new.expires_at is null or new.expires_at > coalesce(new.created_at, now()) + interval '30 days' then
    new.expires_at := coalesce(new.created_at, now()) + interval '30 days';
  end if;

  return new;
end;
$$;

drop trigger if exists requests_guard_insert_trg on public.requests;
create trigger requests_guard_insert_trg
  before insert on public.requests
  for each row
  execute function public.requests_guard_insert();

-- The renter owns the lifecycle; nobody else may retitle or reassign an ask.
-- `requests_update_own` (migration 009) already limits updates to the author,
-- so this only pins the columns the author must not rewrite.
create or replace function public.requests_guard_columns()
returns trigger
language plpgsql
as $$
begin
  new.renter_id := old.renter_id;
  new.created_at := old.created_at;

  if new.status = 'fulfilled' and new.fulfilled_at is null then
    new.fulfilled_at := now();
  end if;
  if new.status <> 'fulfilled' then
    new.fulfilled_at := null;
    new.fulfilled_listing_id := null;
  end if;

  -- Reopening restarts the clock instead of resurrecting an expired ask.
  if new.status = 'open' and old.status <> 'open' then
    new.expires_at := now() + interval '30 days';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists requests_guard_columns_trg on public.requests;
create trigger requests_guard_columns_trg
  before update on public.requests
  for each row
  execute function public.requests_guard_columns();

-- ============================================================
-- 051_request_threads.sql
-- ============================================================

-- A renter who posts "looking for a ladder" had no way of being contacted:
-- messages could only hang off a rental or a listing, so the neighbor who owns
-- the ladder had to publish a listing first just to say "I have one".
--
-- Same shape as the listing threads from 031: the ask is the thread anchor.

alter table public.messages
  add column if not exists request_id uuid references public.requests (id) on delete cascade;

create index if not exists messages_request_id_idx on public.messages (request_id);

alter table public.messages drop constraint if exists messages_thread_check;
alter table public.messages
  add constraint messages_thread_check
  check (rental_id is not null or listing_id is not null or request_id is not null);

-- ============================================================
-- 052_private_rental_documents.sql
-- ============================================================

-- Insurance cards, driver's licences and CDL scans sat in a public bucket.
--
-- `listing-verification` was created with `public = true` so a host could open
-- the renter's proof through a plain URL. The bucket also holds the renter's
-- insurance declaration page, and for vehicles, boats and heavy equipment the
-- licence and endorsement scans that go with it: anyone who guessed or was
-- handed one of those URLs could read the document, forever, signed in or not.
--
-- The bucket becomes private. A document is readable by the person who
-- uploaded it and, when it belongs to a rental, by the other side of that
-- rental — the host still opens the proof before handing the keys over, but
-- through a link that expires.

update storage.buckets set public = false where id = 'listing-verification';

/**
 * Who may read one object in `listing-verification`.
 *
 * Paths are `{uploaderId}/{rentalId|listingId}/{file}`. Runs as the caller on
 * purpose: `public.rentals` has row level security, so the participant check
 * cannot see rentals the caller is not part of even if this were called with a
 * name it has no business asking about.
 */
create or replace function public.can_read_verification_object(object_name text)
returns boolean
language plpgsql
stable
as $$
declare
  segments text[] := string_to_array(coalesce(object_name, ''), '/');
  caller uuid := auth.uid();
  rental_id uuid;
begin
  if caller is null or array_length(segments, 1) is null then
    return false;
  end if;

  -- Your own upload: the renter's proof, the host's QR photo.
  if segments[1] = caller::text then
    return true;
  end if;

  if array_length(segments, 1) < 2 then
    return false;
  end if;

  begin
    rental_id := segments[2]::uuid;
  exception
    when others then
      -- Not a rental document; only the uploader gets it.
      return false;
  end;

  return exists (
    select 1
    from public.rentals r
    where r.id = rental_id
      and (r.owner_id = caller or r.renter_id = caller)
  );
end;
$$;

grant execute on function public.can_read_verification_object(text)
  to anon, authenticated, service_role;

drop policy if exists "listing_verification_public_read" on storage.objects;

drop policy if exists "listing_verification_participant_read" on storage.objects;
create policy "listing_verification_participant_read"
  on storage.objects for select
  using (
    bucket_id = 'listing-verification'
    and public.can_read_verification_object(name)
  );

-- ============================================================
-- 053_rental_settlement_guards.sql
-- ============================================================

-- A participant in a rental could settle it themselves.
--
-- `rentals_update_owner_or_renter` (migration 006) lets the host and the renter
-- update any column on their booking, which the app relies on: dates, PINs, the
-- signed agreement. The same door reaches the columns nobody at the table gets
-- to decide.
--
-- Two holes, one trigger:
--
--   * Money (R2). `stripe_payment_status = 'succeeded'`, a released deposit, a
--     zeroed late fee, an invoice marked paid — all one PATCH away. These are
--     written by the Stripe webhook and the payment routes, which talk to the
--     database as the service role.
--
--   * The handoff (R3). `/api/rentals/confirm-handoff` checks the six-digit PIN
--     before it stamps `host_handed_over_at` and flips the rental to `active`.
--     Writing those columns directly skipped the PIN, so a rental could be
--     started, and closed, without the code ever being said out loud.
--
-- The guard restores the old value instead of raising: the client syncs whole
-- rows, and an error would break a legitimate save that merely echoes a field
-- it never changed.
--
-- What this does not fix: the amounts a fresh booking arrives with
-- (`rental_total_cents`, `deposit_amount_cents`) are still the client's, so the
-- server has nothing but the client's word to charge against. That needs the
-- total computed server-side from the listing and the dates — checklist A1/M1.

/** The rental's own money and the paperwork that proves it was paid. */
create or replace function public.rentals_guard_settlement()
returns trigger
language plpgsql
as $$
declare
  -- Contactless returns complete themselves when the host never turns up to
  -- accept them; the client has always done this, and the rule is checkable
  -- here rather than being taken on trust.
  auto_return_due boolean;
begin
  if public.is_trusted_writer() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- A booking is created before it is paid for. Everything settlement-shaped
    -- starts empty, whatever the client sent.
    new.stripe_payment_intent_id := null;
    new.stripe_payment_status := null;
    new.stripe_deposit_payment_intent_id := null;
    new.deposit_status := null;
    new.deposit_claim_deadline_at := null;
    new.rental_invoices := null;
    new.late_fee_cents := 0;
    new.late_fee_applied_at := null;
    new.no_show_fee_cents := 0;
    new.no_show_marked_at := null;
    new.no_show_renter_notified_at := null;
    new.no_show_automation_at := null;
    new.overdue_hour_notified_at := null;
    new.owner_recovery_notified_at := null;
    new.safely_escalated_at := null;
    new.safely_policy_id := null;
    new.insurance_fee_cents := 0;
    new.cancelled_at := null;
    new.cancelled_by := null;
    new.cancel_refund_percent := null;
    new.cancel_refund_status := null;
    -- Nothing has been handed over yet either.
    new.host_handed_over_at := null;
    new.renter_received_at := null;
    new.renter_returned_at := null;
    new.host_accepted_return_at := null;
    new.picked_up_at := null;
    new.returned_at := null;
    if new.status in ('active', 'overdue', 'completed', 'no_show') then
      new.status := 'pending_approval';
    end if;
    return new;
  end if;

  -- Money: the webhook and the payment routes own every one of these.
  new.stripe_payment_intent_id := old.stripe_payment_intent_id;
  new.stripe_payment_status := old.stripe_payment_status;
  new.stripe_deposit_payment_intent_id := old.stripe_deposit_payment_intent_id;
  new.deposit_status := old.deposit_status;
  new.deposit_amount_cents := old.deposit_amount_cents;
  new.deposit_claim_deadline_at := old.deposit_claim_deadline_at;
  new.rental_total_cents := old.rental_total_cents;
  new.insurance_fee_cents := old.insurance_fee_cents;
  new.safely_policy_id := old.safely_policy_id;
  new.late_fee_cents := old.late_fee_cents;
  new.late_fee_applied_at := old.late_fee_applied_at;
  new.no_show_fee_cents := old.no_show_fee_cents;
  new.cancel_refund_percent := old.cancel_refund_percent;
  new.cancel_refund_status := old.cancel_refund_status;
  -- Invoices decide what the renter is charged after the rental; the host
  -- raises one through `/api/stripe/rental_invoice`, which pays and records it.
  new.rental_invoices := old.rental_invoices;

  -- Who the rental is between, and when it was made, are not editable either.
  new.listing_id := old.listing_id;
  new.owner_id := old.owner_id;
  new.renter_id := old.renter_id;
  new.created_at := old.created_at;

  -- The handoff: stamped by the route that checked the PIN.
  auto_return_due :=
    coalesce(old.booking_mode, '') = 'contactless'
    and old.renter_returned_at is not null
    and old.host_accepted_return_at is null
    and old.renter_returned_at < now() - interval '24 hours';

  new.host_handed_over_at := old.host_handed_over_at;
  new.renter_received_at := old.renter_received_at;
  new.renter_returned_at := old.renter_returned_at;
  new.picked_up_at := old.picked_up_at;

  if auto_return_due then
    -- The renter left it where they were told and the host stayed away: the
    -- rental closes itself rather than hanging on the host forever.
    new.host_accepted_return_at := coalesce(new.host_accepted_return_at, now());
    new.returned_at := coalesce(new.returned_at, old.renter_returned_at);
  else
    new.host_accepted_return_at := old.host_accepted_return_at;
    new.returned_at := old.returned_at;
  end if;

  -- `active` and `completed` are what the PIN buys. The rest of the lifecycle
  -- (approve, decline, cancel, dispute, no-show) stays with the two people
  -- involved. A rental that has already been returned, or whose dispute has
  -- been settled by both sides, may still be closed from either device.
  if new.status <> old.status and new.status in ('active', 'completed') then
    if
      new.status = 'completed'
      and (
        new.returned_at is not null
        or exists (
          select 1
          from public.disputes d
          where d.rental_id = old.id
            and d.status = 'resolved'
        )
      )
    then
      null;
    else
      new.status := old.status;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists rentals_guard_settlement on public.rentals;
create trigger rentals_guard_settlement
  before insert or update on public.rentals
  for each row execute function public.rentals_guard_settlement();

-- ============================================================
-- 054_verification_dispute_notification_guards.sql
-- ============================================================

-- Three claims the client was allowed to make about itself.
--
--   * R6. "QR verified" is a claim that the host printed the tag, put it on
--     the thing and photographed it. The client wrote `qr_verified_at` itself
--     right after the upload, so a direct write said it with no photo at all.
--     `/api/listings/verify-qr` checks the object is in the bucket and stamps
--     the column as the service role.
--
--   * R7. A dispute is meant to end when one side proposes an outcome and the
--     other accepts it — that is the flow the app draws. Nothing enforced it,
--     so a participant could write `status = 'resolved'`, unfreeze the deposit
--     and close the case against themselves in one request.
--
--   * R13. Any signed-in user could insert a notification for any user id, and
--     `listings.owner_id` is public. Free harassment and phishing channel,
--     with the sender's name on it if they felt like typing one.

-- ---------------------------------------------------------------------------
-- R6: verification is stamped by the server that saw the photo.
-- ---------------------------------------------------------------------------

create or replace function public.listings_protect_verification()
returns trigger
language plpgsql
as $$
begin
  if public.is_trusted_writer() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.qr_verified_at := null;
    new.qr_verification_photo_path := null;
  else
    new.qr_verified_at := old.qr_verified_at;
    new.qr_verification_photo_path := old.qr_verification_photo_path;
  end if;
  return new;
end;
$$;

drop trigger if exists listings_protect_verification on public.listings;
create trigger listings_protect_verification
  before insert or update on public.listings
  for each row execute function public.listings_protect_verification();

-- ---------------------------------------------------------------------------
-- R7: a dispute closes when both sides say so.
-- ---------------------------------------------------------------------------

create or replace function public.disputes_guard_resolution()
returns trigger
language plpgsql
as $$
declare
  caller uuid := auth.uid();
  withdrawn_by_opener boolean;
  accepted_by_other_side boolean;
begin
  if public.is_trusted_writer() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- A fresh case is open, the deposit is held, and the person opening it is
    -- the one whose name goes on it.
    new.status := 'open';
    new.deposit_frozen := true;
    new.proposed_outcome := null;
    new.proposed_by := null;
    new.resolution_outcome := null;
    new.resolved_at := null;
    new.resolved_by := null;
    new.acknowledged_by := null;
    if caller is not null then
      new.opened_by := caller;
    end if;
    return new;
  end if;

  new.rental_id := old.rental_id;
  new.opened_by := old.opened_by;
  new.created_at := old.created_at;

  -- You propose in your own name, and you accept in your own name.
  if new.proposed_by is distinct from old.proposed_by and caller is not null then
    new.proposed_by := caller;
  end if;
  if new.acknowledged_by is distinct from old.acknowledged_by and caller is not null then
    new.acknowledged_by := caller;
  end if;

  if new.status = 'resolved' and old.status <> 'resolved' then
    -- The opener can drop their own case at any time.
    withdrawn_by_opener :=
      new.resolution_outcome = 'withdrawn'
      and caller is not null
      and caller = old.opened_by;

    -- Otherwise: one side proposed, the other one accepted.
    accepted_by_other_side :=
      new.resolution_outcome is not null
      and new.proposed_by is not null
      and new.acknowledged_by is not null
      and new.proposed_by <> new.acknowledged_by
      and new.resolution_outcome = coalesce(new.proposed_outcome, new.resolution_outcome);

    if not (withdrawn_by_opener or accepted_by_other_side) then
      -- Reject the resolution, keep the rest of the update.
      new.status := old.status;
      new.resolution_outcome := old.resolution_outcome;
      new.resolved_at := old.resolved_at;
      new.resolved_by := old.resolved_by;
      new.deposit_frozen := old.deposit_frozen;
      return new;
    end if;

    new.resolved_at := now();
  elsif new.status <> 'resolved' then
    -- Only a settled case releases the deposit.
    new.deposit_frozen := old.deposit_frozen;
    new.resolution_outcome := old.resolution_outcome;
    new.resolved_at := old.resolved_at;
    new.resolved_by := old.resolved_by;
  end if;

  return new;
end;
$$;

drop trigger if exists disputes_guard_resolution on public.disputes;
create trigger disputes_guard_resolution
  before insert or update on public.disputes
  for each row execute function public.disputes_guard_resolution();

-- ---------------------------------------------------------------------------
-- R13: you may notify people you have something to do with.
-- ---------------------------------------------------------------------------

drop policy if exists "notifications_insert_any" on public.notifications;
drop policy if exists "notifications_insert_related" on public.notifications;
create policy "notifications_insert_related"
  on public.notifications for insert
  with check (
    auth.uid() is not null
    -- Nobody sends under another name.
    and (actor_id is null or actor_id = auth.uid())
    and (
      -- Reminders and expiry notices you raise for yourself.
      recipient_id = auth.uid()
      -- The other side of a rental you are on.
      or exists (
        select 1
        from public.rentals r
        where (r.owner_id = auth.uid() and r.renter_id = notifications.recipient_id)
           or (r.renter_id = auth.uid() and r.owner_id = notifications.recipient_id)
      )
      -- Somebody you are already talking to.
      or exists (
        select 1
        from public.messages m
        where (m.sender_id = auth.uid() and m.recipient_id = notifications.recipient_id)
           or (m.sender_id = notifications.recipient_id and m.recipient_id = auth.uid())
      )
      -- A host with something on the shelf: bookings, offers and bids reach them.
      or exists (
        select 1 from public.listings l where l.owner_id = notifications.recipient_id
      )
      -- Somebody who asked the neighborhood for a thing.
      or exists (
        select 1 from public.requests q where q.renter_id = notifications.recipient_id
      )
    )
  );

-- A notification arrives unread, and is not a place to paste an essay.
create or replace function public.notifications_guard_insert()
returns trigger
language plpgsql
as $$
begin
  if public.is_trusted_writer() then
    return new;
  end if;

  new.read_at := null;
  new.title := left(coalesce(new.title, ''), 200);
  new.body := left(coalesce(new.body, ''), 1000);
  return new;
end;
$$;

drop trigger if exists notifications_guard_insert on public.notifications;
create trigger notifications_guard_insert
  before insert on public.notifications
  for each row execute function public.notifications_guard_insert();

-- ============================================================
-- 055_narrow_public_reads.sql
-- ============================================================

-- Three tables the public key could read whole.
--
-- Every one of them has a reason to be readable without an account — a guest
-- browsing the neighborhood sees asks, shelves and opening hours. What they
-- did not need is the archive: `select *` with the anon key returned every ask
-- ever posted, the state of every lot including the ones nobody published, and
-- the weekly hours of every host who ever opened the schedule screen. Together
-- that is a map of local demand and a list of when people are out.
--
-- Each policy now returns what the screen shows and nothing behind it.

-- Asks: the live ones. The author always sees their own, closed or expired.
drop policy if exists "requests_select_all" on public.requests;
drop policy if exists "requests_select_live" on public.requests;
create policy "requests_select_live"
  on public.requests for select
  using (
    renter_id = auth.uid()
    or (
      status = 'open'
      and (expires_at is null or expires_at > now())
    )
  );

-- Lot state belongs to a listing; if the listing is not visible to you, its
-- price, its bids and its sale state are not either.
drop policy if exists garage_lot_states_select on public.garage_lot_states;
create policy garage_lot_states_select
  on public.garage_lot_states for select
  using (
    host_id = auth.uid()
    or exists (
      select 1 from public.listings l
      where l.id = garage_lot_states.listing_id
    )
  );

-- Opening hours: only for a garage that is actually open to neighbors. A host
-- who set hours and never went live is not publishing when they are home.
drop policy if exists "garage_sale_schedules_public_read" on public.garage_sale_schedules;
drop policy if exists "garage_sale_schedules_live_read" on public.garage_sale_schedules;
create policy "garage_sale_schedules_live_read"
  on public.garage_sale_schedules for select
  using (
    host_id = auth.uid()
    or exists (
      select 1 from public.garage_storefronts s
      where s.host_id = garage_sale_schedules.host_id
        and s.store_live
    )
  );

-- ============================================================
-- 056_rental_condition_photos.sql
-- ============================================================

-- Condition photos never left the phone that took them.
--
-- At pickup and at return either side can attach a photo of the state the item
-- is in. It went into IndexedDB and stayed there: `pickup_condition_photo` and
-- `return_condition_photo` were local-only fields on the booking, so the other
-- side of the rental opened the rental and read "No photo yet" — and in a
-- dispute over a scratch, the evidence existed on exactly one device, held by
-- one of the two people arguing.
--
-- The photo itself goes to `listing-verification`, the private bucket the
-- insurance documents already use, under `{uploader}/{rental}/condition_*`.
-- Migration 052 made that bucket readable by the uploader and by the other
-- participant of the rental in the path, which is exactly the audience here.
-- The rental row carries the path.

alter table public.rentals
  add column if not exists pickup_condition_photo_path text,
  add column if not exists return_condition_photo_path text;

/**
 * Evidence is written once.
 *
 * A photo of how the item looked at handoff is worth nothing if the other side
 * can replace it afterwards, so once a path is recorded it stays: only the
 * service role can change or clear one. A new path must also point inside the
 * writer's own folder for this rental, or it would be possible to hang someone
 * else's document off your booking.
 */
create or replace function public.rentals_guard_condition_photos()
returns trigger
language plpgsql
as $$
declare
  caller text := coalesce(auth.uid()::text, '');
  path_is_own boolean;
begin
  if public.is_trusted_writer() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- Nothing has been handed over at booking time.
    new.pickup_condition_photo_path := null;
    new.return_condition_photo_path := null;
    return new;
  end if;

  if old.pickup_condition_photo_path is not null then
    new.pickup_condition_photo_path := old.pickup_condition_photo_path;
  elsif new.pickup_condition_photo_path is not null then
    path_is_own :=
      split_part(new.pickup_condition_photo_path, '/', 1) = caller
      and split_part(new.pickup_condition_photo_path, '/', 2) = old.id::text;
    if not path_is_own then
      new.pickup_condition_photo_path := null;
    end if;
  end if;

  if old.return_condition_photo_path is not null then
    new.return_condition_photo_path := old.return_condition_photo_path;
  elsif new.return_condition_photo_path is not null then
    path_is_own :=
      split_part(new.return_condition_photo_path, '/', 1) = caller
      and split_part(new.return_condition_photo_path, '/', 2) = old.id::text;
    if not path_is_own then
      new.return_condition_photo_path := null;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists rentals_guard_condition_photos on public.rentals;
create trigger rentals_guard_condition_photos
  before insert or update on public.rentals
  for each row execute function public.rentals_guard_condition_photos();

-- ============================================================
-- 057_public_profiles.sql
-- ============================================================

-- Nobody could read anybody's name.
--
-- `profiles` has one select policy, `auth.uid() = id` (migration 001), and the
-- app reads that table for other people all over: the host on a listing, the
-- neighbour behind a garage, the other side of a rental, the trust badges on a
-- public profile. Every one of those reads came back empty, so the interface
-- filled the gap with placeholders — "Neighbor", "Host", "Renter", 0.0 stars —
-- and a tapped profile said "not found" for a person who plainly exists.
--
-- Widening the policy is not the answer: row level security is per row, so a
-- policy that let a counterparty read the row would hand them the e-mail, the
-- phone number, the date of birth and the Stripe ids sitting in the same
-- columns. A view is per column, and a view runs with its owner's rights, so
-- `public_profiles` publishes exactly the fields a stranger is meant to see.

create or replace view public.public_profiles as
select
  id,
  display_name,
  rating,
  identity_verified,
  phone_verified,
  created_at
from public.profiles;

-- Read as the view's owner, not the caller: that is the point of the view, and
-- saying it here keeps a future Postgres default from quietly reversing it.
alter view public.public_profiles set (security_invoker = false);

-- Names and badges are shown on listings a guest can browse, so anonymous
-- readers get the same projection. Nothing here is writable.
grant select on public.public_profiles to anon, authenticated, service_role;

comment on view public.public_profiles is
  'Name, rating and trust badges only. The one projection of profiles that is '
  'readable by other people; everything else on profiles stays behind RLS.';

-- ============================================================
-- 058_running_late.sql
-- ============================================================

-- "I'm running late" told nobody.
--
-- The sheet wrote the note onto the renter's own device and raised an in-app
-- notification there — on the phone of the person who typed it. The host, whose
-- copy the sheet quotes ("we'll let them know"), learned nothing, and the
-- no-show clock kept running: two hours after the pickup window the host was
-- being asked to mark a no-show for someone who had said they were on the way.
--
-- The note now lives on the rental, so both sides read the same thing, and it
-- buys the renter an hour before the host is offered the no-show button.
-- The server decides how much of an hour that is: a client that could write
-- `pickup_grace_until` itself could hold a booking open indefinitely.

alter table public.rentals
  add column if not exists running_late_message text;

alter table public.rentals
  add column if not exists running_late_sent_at timestamptz;

alter table public.rentals
  add column if not exists running_late_acknowledged_at timestamptz;

/** How long a heads-up postpones the no-show, and how late it can be sent. */
alter table public.rentals
  add column if not exists pickup_grace_until timestamptz;

create or replace function public.rentals_guard_running_late()
returns trigger
language plpgsql
as $$
declare
  sent_now boolean;
begin
  if public.is_trusted_writer() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- Nobody is late for a pickup that has not been agreed yet.
    new.running_late_message := null;
    new.running_late_sent_at := null;
    new.running_late_acknowledged_at := null;
    new.pickup_grace_until := null;
    return new;
  end if;

  sent_now :=
    new.running_late_sent_at is not null
    and old.running_late_sent_at is distinct from new.running_late_sent_at;

  -- Only the renter is late, and only their own words go in the note.
  if sent_now and auth.uid() is distinct from old.renter_id then
    new.running_late_message := old.running_late_message;
    new.running_late_sent_at := old.running_late_sent_at;
    new.pickup_grace_until := old.pickup_grace_until;
  elsif sent_now then
    new.running_late_sent_at := now();
    new.running_late_message := left(coalesce(new.running_late_message, ''), 500);
    -- One hour from the heads-up, and never more than four hours past the
    -- pickup window: being told twice is not a reason to wait all day.
    new.pickup_grace_until := coalesce(
      old.pickup_grace_until,
      least(
        now() + interval '1 hour',
        coalesce(old.pickup_at, now()) + interval '4 hours'
      )
    );
  else
    new.running_late_message := old.running_late_message;
    new.running_late_sent_at := old.running_late_sent_at;
    new.pickup_grace_until := old.pickup_grace_until;
  end if;

  -- Acknowledging is the host's to do, and only once.
  if
    new.running_late_acknowledged_at is distinct from old.running_late_acknowledged_at
    and (
      old.running_late_acknowledged_at is not null
      or auth.uid() is distinct from old.owner_id
      or old.running_late_sent_at is null
    )
  then
    new.running_late_acknowledged_at := old.running_late_acknowledged_at;
  elsif new.running_late_acknowledged_at is distinct from old.running_late_acknowledged_at then
    new.running_late_acknowledged_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists rentals_guard_running_late on public.rentals;
create trigger rentals_guard_running_late
  before insert or update on public.rentals
  for each row execute function public.rentals_guard_running_late();

-- ============================================================
-- 059_listing_delete_guard.sql
-- ============================================================

-- Deleting a listing deleted the rentals on it.
--
-- `rentals.listing_id` cascades (migration 006), so "Delete listing" on a
-- listing with an item currently out on rent removed the booking itself: the
-- renter's copy of the deal, the handoff PINs, the deposit record, the invoices,
-- the dispute it was attached to. The host holding a paid rental could erase it
-- from both sides with one button, and nothing about the money it had taken.
--
-- A listing with a rental that still occupies the calendar cannot be deleted at
-- all. The same statuses `rentals_reject_overlap` treats as busy: the ones
-- where the item is booked, out, late, or being argued over. Once every rental
-- on it is finished or cancelled the listing deletes as before, taking its
-- history with it.
--
-- Pausing is untouched: a host may stop taking new bookings at any time, and
-- the rental already running is unaffected.

create or replace function public.listings_block_delete_with_live_rental()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  live_count integer;
begin
  select count(*)::integer
  into live_count
  from public.rentals r
  where r.listing_id = old.id
    and r.status in (
      'pending_approval',
      'pending_checkin',
      'active',
      'upcoming',
      'overdue',
      'disputed',
      'no_show'
    );

  if live_count > 0 then
    raise exception
      'This listing has % rental(s) that are booked, out, or in dispute. Finish or cancel them before deleting it.',
      live_count
      using errcode = 'P0001';
  end if;

  return old;
end;
$$;

drop trigger if exists listings_block_delete_with_live_rental on public.listings;
create trigger listings_block_delete_with_live_rental
  before delete on public.listings
  for each row execute function public.listings_block_delete_with_live_rental();

